version: '3'
services:
  sync:
    depends_on:
      - amid
      - asterisk-ajam
      - asterisk-ami
      - auth
      - rabbitmq
    environment:
      TARGETS: "asterisk-ajam:5039 asterisk-ami:5038 asterisk-ami:8123 amid:9491 auth:9497 rabbitmq:5672"
