version: '3'
services:
  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  amid:
    image: wazo-amid-tests
    ports:
      - 9491
    environment:
      XIVO_UUID: "00000000-0000-4000-8000-0000000AA450"
    volumes:
      - "../..:/usr/src/wazo-amid"
      - "./etc/wazo-amid/conf.d/50-default.yml:/etc/wazo-amid/conf.d/50-default.yml"
      # - "${LOCAL_GIT_REPOS}/xivo-bus/xivo_bus:/opt/venv/lib/python3.9/site-packages/xivo_bus"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/opt/venv/lib/python3.9/site-packages/xivo"

  asterisk-ajam:
    image: wazoplatform/flask
    ports:
      - 5039
    volumes:
      - "./asterisk-ajam:/usr/local/share/asterisk-ajam"
    command: "python /usr/local/share/asterisk-ajam/mock-asterisk-ajam.py 5039"

  asterisk-ami:
    image: wazoplatform/flask
    ports:
      - 5038
      - 8123
    volumes:
      - "./asterisk-ami:/usr/local/share/asterisk-ami"
    command: "python /usr/local/share/asterisk-ami/mock-asterisk-ami.py --http_port 8123 --ami_port 5038"

  auth:
    image: "wazoplatform/wazo-auth-mock"
    ports:
      - 9497

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672
    volumes:
      - type: tmpfs
        target: /var/lib/rabbitmq
