version: '3'
services:
  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  amid:
    image: wazo-amid-tests
    ports:
      - "9491"
    environment:
      XIVO_UUID: "00000000-0000-4000-8000-0000000AA450"
    volumes:
      - "../..:/usr/src/wazo-amid"
      - "./etc/wazo-amid/conf.d/50-default.yml:/etc/wazo-amid/conf.d/50-default.yml"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/opt/venv/lib/python3.7/site-packages/xivo"

  asterisk-ajam:
    image: p0bailey/docker-flask
    ports:
      - "5040"
    volumes:
      - "./ssl/asterisk-ajam:/usr/local/share/asterisk-ajam-ssl"
      - "./asterisk-ajam:/usr/local/share/asterisk-ajam"
    command: "python /usr/local/share/asterisk-ajam/mock-asterisk-ajam.py 5040"

  auth:
    image: "wazoplatform/wazo-auth-mock"
    ports:
      - "9497"
