# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/wazo-amid/conf.d/

# Owner of the process
user: wazo-amid

# Enable debug level logs
debug: False

# Enable forwarding of AMI events to the event bus
publish_ami_events: True

# Connection info to Asterisk AMI
ami:
  host: localhost
  port: 5038
  username: wazo_amid
  password: eeCho8ied3u

# Connection info to Asterisk AJAM
ajam:
  host: localhost
  port: 5039
  https: false
  username: wazo_amid
  password: eeCho8ied3u

# Connection info to the authentication server
auth:
  host: localhost
  port: 9497
  prefix: null
  https: false

# Connection info to the event bus (AMQP)
bus:
  host: localhost
  port: 5672
  username: guest
  password: guest
  vhost: /
  exchange_name: wazo-headers

# REST API server
rest_api:
  # Listening address
  listen: 127.0.0.1

  # Listening port
  port: 9491

  # SSL files
  certificate: null
  private_key: null

  #CORS configuration. See Flask-CORS documentation for other values.
  cors:

    #Enabled by default
    enabled: True

    #Allow JSON preflight requests
    allow_headers: [Content-Type, X-Auth-Token]
